# Generated by Django 5.0.6 on 2024-06-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_admin_user_is_staff_remove_user_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
